version: "3"
services: 
    node-app:
        build: .
        ports:
            - "5000:5000"
        environment:
            - PORT=5000

    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=ezioguga
            - MONGO_INITDB_ROOT_PASSWORD=Asd123+
        volumes:
            # Named Anonymous Volume
            - mongo-db:/data/db

volumes:
    mongo-db: